---
  - name: Unset apache in maintenance mode
    lineinfile: >
      dest="{{ apache_sysconfig }}"
      line="{{ apache_sysconfig_regex_unset }}"
      regexp="{{ apache_sysconfig_regex }}"
    notify:
      - restart-apache2
    tags:
      - apache
