---
  - name: Set apache in maintenance mode
    lineinfile: >
      dest="{{ apache_sysconfig }}"
      line="{{ apache_sysconfig_regex_set }}"
      regexp={{ apache_sysconfig_regex }}
    notify:
      - restart-apache2
    tags:
      - apache
