---
  - name: There is new update available
    # We run this command locally
    # TODO the staging host to decide if we have to deal with the vm 
    # or production server
    shell: "{{ check_migration_command }}"
    delegate_to: localhost
    register: migration_available
    ignore_errors: False
    block:
      - name: Run migrations
        shell: source /root/.bashrc && run_in_api rails db:migrate
      - name: Run data migrations
        shell: source /root/.bashrc && run_in_api rails db:migrate:with_data
    when: migration_available.rc == 1
