- name: restart-apache2
  service: 
    name=apache2 state=restarted
  tags:
    - apache2

- name: debug task
  debug:
    msg: "Called for {{inventory_hostname}}"
  listen: ensure systemd

- name: obs-delayed-consistency-check
  service: state=started name="{{item}}"
  listen: ensure systemd
  loop: "{{systemd_services}}"

- name: notify rocketchat
  shell: "bin/dotenv utilities/send_rocketchat_message {{ ansible_ssh_host }}"
  delegate_to: localhost
  listen: rocket chat

- name: run curl
  # change the url for
  shell: "{{check_url}}"
  delegate_to: localhost
  listen: check_http_server_running

